import type { Metadata } from 'next'
import { Inter, Montserrat, Sarabun } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Homepage/Navbar'

const montserrat = Montserrat({
  weight: ['400', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
