import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserContextProvider } from "@/model/User";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <Navbar profileImage="/meen.png" />
          <div className="mt-[4rem]"></div>

          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
